### ISSUE TITLE
npm install points to https://github.com/bchelli/node-smb2

### ISSUE THREAD

**Issue by ClaytonSmith** [Node-SMB/marsaud-smb2#16]
`npm install -S smb2` installs [bchelli's](https://github.com/bchelli) instance of smb2.

Perhaps use `npm install -S git+https://github.com/Node-SMB/marsaud-smb2.git` or rename the package

**Comment by julien-f** [comment]
The package is also available as `@marsaud/smb2`, but you're right, we should update the README :)

**Comment by ClaytonSmith** [comment]
Out of curiosity,  is this the official version of smb2?

**Comment by julien-f** [comment]
What do you mean?

This is a fork of bchelli's smb2, but I'd like to see them merged :)

**Comment by ClaytonSmith** [comment]
Given that the project name is Node-SMB, I was wondering if this is the new home of smb2.

**Comment by julien-f** [comment]
@ClaytonSmith I created this org last week to group the libs related to Node and SMB but it's a work in progress and it's up to current maintainers to move their repo here (if they want to). :)

**Comment by ClaytonSmith** [comment]
Your work is greatly appreciated :)
