### ISSUE TITLE
Create multiple level folder

### ISSUE THREAD

**Issue by salmenbej** [Node-SMB/marsaud-smb2#17]
Is it possibile to create a multiple level folder like \\folder1\\folder2\\folder3?
Like for fs-extra there is fs.mkdirs.

**Comment by vdiez** [comment]
you can use [ensureDir](https://github.com/Node-SMB/marsaud-smb2#smb2clientensuredir--path-callback-)

**Comment by salmenbej** [comment]
@vdiez thanks ;), It works.
