### ISSUE TITLE
Checking files by wildcard

### ISSUE THREAD

**Issue by eyzi** [Node-SMB/marsaud-smb2#47]
Is it possible to search file by wildcard? eg, ABC*.*_final would match ABC._final, ABC.js_final and ABC2019.js_final.

**Comment by julien-f** [comment]
Hi,

It's not supported directly but you should be able to easily do it yourself using `readdir` and a lib like [`micromatch`](https://github.com/micromatch/micromatch/blob/master/README.md):

```js
async function glob(smb2Client, dir, pattern) {
  const entries = await smb2Client.readdir(dir)
  return micromatch(entries, pattern)
}
```
