### ISSUE TITLE
readdir only lists 510 items

### ISSUE THREAD

**Issue by eyzi** [Node-SMB/marsaud-smb2#49]
Hi, I was wondering why my program kept saying the file doesn't exist while I can confirm that it does in the shared folder. Upon trial and error, I found that the `.readdir()` function only lists the first 510 items while I have 3002 items in my shared folder and the file I'm looking for is near the bottom.

Is there a way to get the complete list of files using the `.readdir()` function or at least sort the files in descending order first before getting the list?

Thanks.

**Comment by DRKRahul** [comment]
Facing same issue,  I have 597 items in my shared folder but able to read only 480 items

**Comment by julien-f** [comment]
The PR #50 should solve this issue, can you please test it?

**Comment by DRKRahul** [comment]
> The PR #50 should solve this issue, can you please test it?

It worked
