### ISSUE TITLE
Readme - Example of createWriteStream is wrong

### ISSUE THREAD

**Issue by orekav** [Node-SMB/marsaud-smb2#51]
```
smb2Client.createWriteStream('path\\to\\the\\file', function(err, readStream) {
    if (err) throw err;
    var readStream = fs.createReadStream('localFile');
    readStream.pipe(writeStream);
});
```
Should be

```
smb2Client.createWriteStream('path\\to\\the\\file', function(err, writeStream) {
    if (err) throw err;
    var readStream = fs.createReadStream('localFile');
    readStream.pipe(writeStream);
});
```

Also, in order to use this library it should say
const SMB2 = require("@marsaud/smb2");
instead of 
const SMB2 = require("smb2");

**Comment by julien-f** [comment]
Indeed, please [create a PR for this](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), you can do so very easily by [editing the file online](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository), thank you 🙂

**Comment by orekav** [comment]
Done

**Comment by julien-f** [comment]
Thank you!
