### ISSUE TITLE
check path is Directory or file

### ISSUE THREAD

**Issue by mogadanez** [Node-SMB/marsaud-smb2#53]
is it possible  to check path is Directory or file
ideally -  readdir  with advanced properties  like dir|file, size, etc

**Comment by koush** [comment]
The information is there but it is scrubbed before being returned.

https://github.com/koush/marsaud-smb2/commit/308a33b3c05a43c1ebdfa9d8c998e85634784b29

**Comment by PachVerb** [comment]
> The information is there but it is scrubbed before being returned.
> 
> 
> 
> https://github.com/koush/marsaud-smb2/commit/308a33b3c05a43c1ebdfa9d8c998e85634784b29
 is this commit  is your product? I want to use it on   
my project

**Comment by koush** [comment]
yeah go ahead and use it

**Comment by PachVerb** [comment]
> yeah go ahead and use it

Hi, I used him on the project and it worked well. But the returned file meta-information is a buffer buffer flow. How do you parse it to be readable?  do you know? help

**Comment by sachinraste** [comment]
FIleName : readdir.js

When you modify the readdir.js  you will get the parsed output. [{obj1},{obj2}]

NOTE : 
```js
//FileAttributes = 16 = Directory
//FileAttributes = 32 = File
```

```js
var BigInt = require('../tools/bigint');
```

```js
filesBatch.push(files.map(function (v) {
              // get the filename only
              v.CreationTime = convert(BigInt.fromBuffer(v.CreationTime).toNumber())
              v.LastAccessTime = convert(BigInt.fromBuffer(v.LastAccessTime).toNumber())
              v.LastWriteTime = convert(BigInt.fromBuffer(v.LastWriteTime).toNumber())
              v.ChangeTime = convert(BigInt.fromBuffer(v.ChangeTime).toNumber())
              v.EndofFile = v.EndofFile.toString()
              v.AllocationSize= BigInt.fromBuffer(v.AllocationSize).toNumber()
             return v;
            })
            .filter(function (v) {
              // remove '.' and '..' values
              return v.Filename !== '.' && v.Filename !== '..';
            })
        );
```

```js
function convert(time) {
    var winTicks = 10000000;
    var uEpoch = 11644473600;
    var unixTime = time / winTicks - uEpoch;
    var utc = new Date(unixTime * 1000).toUTCString();
    return utc
  }
```

**Comment by vdiez** [comment]
this should now be possible with 0.17

Thanks @sachinraste for the idea

I think we can close this
