### ISSUE TITLE
isDirectory not working

### ISSUE THREAD

**Issue by nerminator** [Node-SMB/marsaud-smb2#68]
when we call readdir with options : {stats:true},  calling isDirectory for a file in files array is always returning  false.

The problem is in tools/stats.js:
line 17:
`return attr === DIRECTORY;`
should be :
`(attr & DIRECTORY) == DIRECTORY`

**Comment by julien-f** [comment]
Thanks for your report, a PR would be most welcome :slightly_smiling_face:

**Comment by vdiez** [comment]
you're right, it's a mask.

Didn't think of it, as my server did not return other values aside of 16. If you can, as @julien-f said please provide PR. Otherwise I will next week
