### ISSUE TITLE
How to can i get current working directory?

### ISSUE THREAD

**Issue by azamsolix** [Node-SMB/marsaud-smb2#71]
Hi sir,
How can i get current working directory?
Is there any method or something from which i can get current working directory?
Thanks
Azam

**Comment by julien-f** [comment]
AFAIK, there is no notion of current working directory in SMB, and this library does not implement one on top of it.

**Comment by azamsolix** [comment]
Okay Julien,
Is there any other way or alternative to get it?
Thanks
Azam

**Comment by julien-f** [comment]
There is no current working directory to get.
